/**
 * English locale (local management UI)
 */
export default {
  common: { loading: 'Loading…', back: 'Back', refresh: 'Refresh' },
  nav: { overview: 'Overview', chat: 'Chat', employees: 'Employees', settings: 'Settings', bindAccount: 'Bind account', logout: 'Log out', owner: 'Owner' },
  home: { title: 'Overview', currentTeam: 'Current team', owner: 'Owner', employeeCount: '{n} employee(s)', noEmployees: 'No employees yet. Create one on the Employees page.' },
  chat: { title: 'Chat with employee', selectEmployee: 'Select employee', selectPlaceholder: 'Select employee', inputMessage: 'Message', inputPlaceholder: 'Type and press Enter to send', send: 'Send', usageTemplate: 'Usage: {input} in / {output} out tokens', sendFailed: 'Send failed' },
  employees: { title: 'Employees', create: 'Create employee', list: 'Employee list', name: 'Name', namePlaceholder: 'Employee name', persona: 'Persona (optional)', personaPlaceholder: 'e.g. friendly, professional', role: 'Role (optional)', rolePlaceholder: 'e.g. assistant, analyst', specialty: 'Specialty (optional)', specialtyPlaceholder: 'e.g. writing, data', createBtn: 'Create', noEmployees: 'No employees.', createFailed: 'Create failed', viewLogs: 'Logs', viewMemory: 'Memory' },
  logs: { title: 'Run logs', backToEmployees: 'Back to employees', empty: 'No logs yet. Use CLI (joytrunk chat) or chat here to generate logs.', loadFailed: 'Load failed', runId: 'Run', event: 'Event', time: 'Time', payload: 'Details', eventLoopStart: 'Loop start', eventIteration: 'Iteration', eventLlmRequest: 'LLM request', eventLlmResponse: 'LLM response', eventToolCalls: 'Tool calls', eventToolResult: 'Tool result', eventFinalReply: 'Final reply', eventMaxIterations: 'Max iterations', eventLoopDone: 'Loop done', eventAppendTurnDone: 'History saved', sortOrder: 'Sort', sortNewestFirst: 'Newest first', sortOldestFirst: 'Oldest first', filterByEvent: 'Event type', filterByRunId: 'Run ID', filterByKeyword: 'Keyword', filterPlaceholderRunId: 'Filter by run_id', filterPlaceholderKeyword: 'Search in payload', filterAllEvents: 'All events', resultCount: '{n} entries' },
  memory: { title: 'Memory DB', backToEmployees: 'Back to employees', empty: 'No memory data', loadFailed: 'Load failed', employeeNotFound: 'Employee not found or no access; if you just updated the server, restart joytrunk server and refresh.', categories: 'Categories', items: 'Items', resources: 'Resources', relations: 'Category–Item relations', chatMessages: 'Chat messages', sessionKey: 'Session', role: 'Role', content: 'Content', id: 'ID', createdAt: 'Created', add: 'Add', edit: 'Edit', delete: 'Delete', save: 'Save', cancel: 'Cancel', createCategory: 'New category', createItem: 'New item', createResource: 'New resource', createRelation: 'New relation', name: 'Name', description: 'Description', summary: 'Summary', url: 'URL', modality: 'Modality', caption: 'Caption', memoryType: 'Memory type', itemId: 'Item ID', categoryId: 'Category ID', confirmDelete: 'Delete?', success: 'Done', failed: 'Failed', noItemsInCategory: 'No items', addItemToCategory: 'Add item' },
  notFound: { title: 'Page not found', hint: 'The link may be invalid or not included in the current build.', backHome: 'Back to home' },
  settings: { title: 'Settings', language: 'Language', theme: 'Theme', themeLight: 'Light', themeDark: 'Dark', usage: 'Usage', usageRouter: 'Router: {n} tokens', usageCustom: 'Custom LLM: {n} tokens (no charge)', customLLM: 'Custom LLM (optional)', customLLMHint: 'When set, employees use your API; requests do not go through JoyTrunk Router.', apiKey: 'API Key', baseUrl: 'Base URL', model: 'Model', save: 'Save', restoreDefault: 'Restore default', saveFailed: 'Save failed', restoreFailed: 'Restore failed' },
  login: { subtitle: 'Bind account (optional) — for JoyTrunk IM', login: 'Log in', hint: 'Single local user: click to use current owner.', register: 'Register owner', name: 'Name', namePlaceholder: 'Owner name', email: 'Email (optional)', emailPlaceholder: 'email', switchToRegister: 'No account? Register', switchToLogin: 'Have an account? Log in', loginFailed: 'Log in failed', registerFailed: 'Register failed' },
}
